# Generated by Django 5.1.7 on 2025-04-02 01:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('bank_acc', models.IntegerField(unique=True)),
                ('mission_statement', models.TextField(max_length=300)),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharityUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='gvt_docs/')),
                ('uploaded_date', models.DateField(default=django.utils.timezone.now)),
                ('charity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gvt_doc', to='charity.charity')),
            ],
        ),
    ]
