# Generated by Django 5.2 on 2025-05-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='guest_email',
        ),
    ]
