# Generated by Django 5.2 on 2025-05-02 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_remove_donations_guest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityPhases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_phases', to='charity.charity')),
            ],
        ),
    ]
