# Generated by Django 5.2 on 2025-05-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_charityphases'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donations',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Mixx', 'Mixx'), ('Airtel Money', 'Airtel Money'), ('T Pesa', 'T Pesa'), ('M Pesa', 'M Pesa'), ('Halopesa', 'HaloPesa')], max_length=15),
        ),
    ]
