# Generated by Django 5.2 on 2025-05-03 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_donations_phone_donations_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity', to='charity.charity'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donations',
            name='vendor',
            field=models.CharField(blank=True, choices=[('M Pesa', 'M Pesa'), ('HaloPesa', 'HaloPesa'), ('T Pesa', 'T Pesa'), ('Mixx', 'Mixx'), ('Airtel Money', 'Airtel Money')], max_length=15),
        ),
    ]
