# Generated by Django 5.2 on 2025-05-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_alter_donations_charity_alter_donations_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donations',
            name='vendor',
            field=models.CharField(choices=[('Airtel Money', 'Airtel Money'), ('Mixx', 'Mixx'), ('T Pesa', 'T Pesa'), ('HaloPesa', 'HaloPesa'), ('M Pesa', 'M Pesa')], max_length=15),
        ),
    ]
